// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "petadopter/domain"

	mock "github.com/stretchr/testify/mock"
)

// SpeciesUsecase is an autogenerated mock type for the SpeciesUsecase type
type SpeciesUsecase struct {
	mock.Mock
}

// AddSpecies provides a mock function with given fields: newSpecies
func (_m *SpeciesUsecase) AddSpecies(newSpecies domain.Species) (int, error) {
	ret := _m.Called(newSpecies)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.Species) int); ok {
		r0 = rf(newSpecies)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Species) error); ok {
		r1 = rf(newSpecies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSpecies provides a mock function with given fields: id
func (_m *SpeciesUsecase) DeleteSpecies(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllSpecies provides a mock function with given fields:
func (_m *SpeciesUsecase) GetAllSpecies() ([]domain.Species, error) {
	ret := _m.Called()

	var r0 []domain.Species
	if rf, ok := ret.Get(0).(func() []domain.Species); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Species)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSpecies provides a mock function with given fields: id, UpdateSpecies
func (_m *SpeciesUsecase) UpdateSpecies(id int, UpdateSpecies domain.Species) (int, error) {
	ret := _m.Called(id, UpdateSpecies)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, domain.Species) int); ok {
		r0 = rf(id, UpdateSpecies)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.Species) error); ok {
		r1 = rf(id, UpdateSpecies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSpeciesUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewSpeciesUsecase creates a new instance of SpeciesUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSpeciesUsecase(t mockConstructorTestingTNewSpeciesUsecase) *SpeciesUsecase {
	mock := &SpeciesUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
