// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "petadopter/domain"

	mock "github.com/stretchr/testify/mock"
)

// SpeciesData is an autogenerated mock type for the SpeciesData type
type SpeciesData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *SpeciesData) Delete(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *SpeciesData) GetAll() ([]domain.Species, error) {
	ret := _m.Called()

	var r0 []domain.Species
	if rf, ok := ret.Get(0).(func() []domain.Species); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Species)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertSpecies provides a mock function with given fields: newSpecies
func (_m *SpeciesData) InsertSpecies(newSpecies domain.Species) (int, error) {
	ret := _m.Called(newSpecies)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.Species) int); ok {
		r0 = rf(newSpecies)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Species) error); ok {
		r1 = rf(newSpecies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, updatedData
func (_m *SpeciesData) Update(id int, updatedData domain.Species) (int, error) {
	ret := _m.Called(id, updatedData)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, domain.Species) int); ok {
		r0 = rf(id, updatedData)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.Species) error); ok {
		r1 = rf(id, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSpeciesData interface {
	mock.TestingT
	Cleanup(func())
}

// NewSpeciesData creates a new instance of SpeciesData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSpeciesData(t mockConstructorTestingTNewSpeciesData) *SpeciesData {
	mock := &SpeciesData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
